// Data-source layer. Delegates all YouTube interaction to the `yt-dlp`
// CLI binary on the user's PATH, then shapes the result into the same
// SubtitleResult contract the previous regex-based scraper exposed.
//
// Two stages per call:
//   1. `yt-dlp -J --skip-download URL` → metadata, chapters, available subs.
//   2. `yt-dlp --write-subs --write-auto-subs --sub-lang LANG --sub-format vtt
//       --skip-download --paths TMP URL` → VTT file in a tempdir; we read
//       and parse it, then clean up the tempdir.
//
// Subprocess + filesystem operations use Node stdlib only (execFile, fs.rm,
// fs.mkdtemp, fs.readdir, fs.readFile) — no spawn-rx, no rimraf.
//
// The yt-dlp delegation pattern is borrowed from anaisbetts/mcp-youtube.

import { execFile as execFileCallback } from "node:child_process";
import { promisify } from "node:util";
import {
  mkdtemp,
  readFile,
  readdir,
  rm,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { parseVtt, TranscriptLine } from "./vtt-parser.js";

const execFile = promisify(execFileCallback);

export interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface AdChapter {
  title: string;
  startMs: number;
  endMs: number;
}

export interface VideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  publishDate: string;
}

export interface SubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
}

const YT_DLP_TIMEOUT_MS = 60_000;
// yt-dlp -J output for long videos can be megabytes (chapters, formats, etc).
const YT_DLP_MAX_BUFFER = 64 * 1024 * 1024;
// End-time fallback when an ad chapter is the last chapter in the video.
const TRAILING_AD_FALLBACK_MS = 5 * 60 * 1000;

const AD_MARKERS: ReadonlyArray<string> = [
  "(werbung)", "(ad)", "(ads)", "(sponsor)", "(sponsored)",
  "(promo)", "(promotion)", "(anzeige)", "(reklame)",
  "[werbung]", "[ad]", "[ads]", "[sponsor]", "[sponsored]",
  "[promo]", "[promotion]", "[anzeige]", "[reklame]",
];

export interface YtDlpInfo {
  title?: string;
  uploader?: string;
  channel?: string;
  channel_follower_count?: number;
  view_count?: number;
  upload_date?: string; // YYYYMMDD
  subtitles?: Record<string, unknown>;
  automatic_captions?: Record<string, unknown>;
  chapters?: Array<{
    start_time: number;
    end_time?: number;
    title: string;
  }>;
}

/**
 * Wraps a child_process error so the message exposes yt-dlp's stderr instead
 * of just "Command failed". We only keep the first non-empty stderr line —
 * that's where yt-dlp puts its top-level reason ("ERROR: …").
 */
function describeYtDlpError(err: unknown): string {
  const e = err as NodeJS.ErrnoException & { stderr?: string };
  const stderr = (e.stderr || "").trim();
  if (stderr) {
    const firstLine = stderr.split(/\r?\n/).find((l) => l.trim().length > 0);
    if (firstLine) return firstLine.replace(/^ERROR:\s*/i, "");
  }
  return e.message || String(err);
}

/**
 * Run `yt-dlp -J --skip-download URL` and parse the metadata JSON.
 */
async function fetchVideoInfo(url: string): Promise<YtDlpInfo> {
  let stdout: string;
  try {
    const result = await execFile(
      "yt-dlp",
      ["-J", "--skip-download", url],
      { timeout: YT_DLP_TIMEOUT_MS, maxBuffer: YT_DLP_MAX_BUFFER },
    );
    stdout = result.stdout;
  } catch (err) {
    throw new Error(`yt-dlp metadata fetch failed: ${describeYtDlpError(err)}`);
  }

  try {
    return JSON.parse(stdout) as YtDlpInfo;
  } catch (err) {
    throw new Error(
      `yt-dlp returned non-JSON output: ${(err as Error).message}. Preview: ${stdout.slice(0, 200)}`,
    );
  }
}

/**
 * Flatten yt-dlp's manual `subtitles` and `automatic_captions` maps into a
 * single CaptionTrack[]. Manual entries take precedence when the same
 * language code appears in both.
 */
export function extractCaptionTracks(info: YtDlpInfo): CaptionTrack[] {
  const tracks: CaptionTrack[] = [];
  const seen = new Set<string>();

  for (const code of Object.keys(info.subtitles || {})) {
    if (!seen.has(code)) {
      tracks.push({ languageCode: code, name: code, isAutoGenerated: false });
      seen.add(code);
    }
  }

  for (const code of Object.keys(info.automatic_captions || {})) {
    if (!seen.has(code)) {
      tracks.push({ languageCode: code, name: code, isAutoGenerated: true });
      seen.add(code);
    }
  }

  return tracks;
}

/**
 * Pick out chapters whose title matches one of the ad markers. End time
 * comes from the chapter's own end_time, or the next chapter's start, or a
 * 5-minute fallback for a trailing ad chapter.
 */
export function extractAdChapters(info: YtDlpInfo): AdChapter[] {
  const chapters = info.chapters || [];
  const adChapters: AdChapter[] = [];

  for (let i = 0; i < chapters.length; i++) {
    const chapter = chapters[i];
    const titleLower = (chapter.title || "").toLowerCase();
    const isAd = AD_MARKERS.some((marker) => titleLower.includes(marker));
    if (!isAd) continue;

    const next = chapters[i + 1];
    const endSeconds =
      typeof chapter.end_time === "number"
        ? chapter.end_time
        : next?.start_time ?? chapter.start_time + TRAILING_AD_FALLBACK_MS / 1000;

    adChapters.push({
      title: chapter.title,
      startMs: Math.round(chapter.start_time * 1000),
      endMs: Math.round(endSeconds * 1000),
    });
  }

  return adChapters;
}

function shorten(value: number): string {
  if (value >= 1_000_000) return (value / 1_000_000).toFixed(1) + "M";
  if (value >= 1_000) return (value / 1_000).toFixed(1) + "k";
  return String(value);
}

export function extractMetadata(info: YtDlpInfo): VideoMetadata {
  const subs =
    typeof info.channel_follower_count === "number"
      ? shorten(info.channel_follower_count)
      : "";

  const views =
    typeof info.view_count === "number" ? shorten(info.view_count) : "";

  const date = info.upload_date || "";
  const publishDate =
    date.length === 8
      ? `${date.slice(0, 4)}-${date.slice(4, 6)}-${date.slice(6, 8)}`
      : "";

  return {
    title: info.title || "",
    author: info.uploader || info.channel || "",
    subscriberCount: subs,
    viewCount: views,
    publishDate,
  };
}

/**
 * Returns available caption languages for a video without fetching the full
 * transcript.
 */
export async function getAvailableLanguages(
  videoID: string,
): Promise<CaptionTrack[]> {
  if (!videoID || typeof videoID !== "string") {
    throw new Error("Invalid video ID: must be a non-empty string");
  }
  const info = await fetchVideoInfo(`https://www.youtube.com/watch?v=${videoID}`);
  return extractCaptionTracks(info);
}

/**
 * Fetches the transcript for the given video and language.
 *
 * If the requested language is not available and `enableFallback` is true,
 * tries English first, then falls back to the first available language.
 */
export async function getSubtitles(options: {
  videoID: string;
  lang?: string;
  enableFallback?: boolean;
}): Promise<SubtitleResult> {
  const { videoID, lang = "en", enableFallback = true } = options;

  if (!videoID || typeof videoID !== "string") {
    throw new Error("Invalid video ID: must be a non-empty string");
  }

  const url = `https://www.youtube.com/watch?v=${videoID}`;

  // Stage 1 — metadata, chapters, available subs.
  const info = await fetchVideoInfo(url);
  const availableLanguages = extractCaptionTracks(info);
  const adChapters = extractAdChapters(info);
  const metadata = extractMetadata(info);

  // Pick target language with fallback.
  let targetLang = lang;
  if (availableLanguages.length > 0) {
    const hasRequested = availableLanguages.some(
      (t) => t.languageCode === lang,
    );

    if (!hasRequested && enableFallback) {
      const hasEnglish = availableLanguages.some(
        (t) => t.languageCode === "en",
      );
      if (hasEnglish) {
        targetLang = "en";
        console.error(
          `[youtube-fetcher] Language '${lang}' not available, falling back to 'en'`,
        );
      } else {
        targetLang = availableLanguages[0].languageCode;
        console.error(
          `[youtube-fetcher] Language '${lang}' not available, falling back to '${targetLang}'`,
        );
      }
    } else if (!hasRequested) {
      throw new Error(
        `Language '${lang}' not available. Available: ${availableLanguages.map((t) => t.languageCode).join(", ")}`,
      );
    }
  }

  // Stage 2 — download the VTT for the chosen language into a tempdir.
  const tempDir = await mkdtemp(join(tmpdir(), "youtube-transcript-"));
  let lines: TranscriptLine[] = [];

  try {
    try {
      await execFile(
        "yt-dlp",
        [
          "--write-subs",
          "--write-auto-subs",
          "--sub-lang",
          targetLang,
          "--sub-format",
          "vtt",
          "--skip-download",
          "-o",
          "%(id)s.%(ext)s",
          "--paths",
          tempDir,
          url,
        ],
        { timeout: YT_DLP_TIMEOUT_MS, maxBuffer: YT_DLP_MAX_BUFFER },
      );
    } catch (err) {
      throw new Error(
        `yt-dlp subtitle download failed: ${describeYtDlpError(err)}`,
      );
    }

    const files = await readdir(tempDir);
    const vttFile = files.find((name) => name.endsWith(".vtt"));
    if (!vttFile) {
      throw new Error(
        "No transcript available for this video. The video may not have captions enabled.",
      );
    }

    const vttContent = await readFile(join(tempDir, vttFile), "utf-8");
    lines = parseVtt(vttContent);

    if (lines.length === 0) {
      throw new Error("Transcript file was empty after parsing.");
    }
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }

  return {
    lines,
    requestedLang: lang,
    actualLang: targetLang,
    availableLanguages,
    adChapters,
    metadata,
  };
}
